In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"D:\Besant Technologies\MLP\sales_data_sample.csv")

In [3]:
df

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType
0,1,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular
1,2,2025-01-02,South,Meena,Mouse,5,800,0,Accessories,New
2,3,2025-01-03,East,Ajay,Keyboard,3,1200,10,Accessories,Regular
3,4,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular
4,5,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New
5,6,2025-01-06,East,Rahul,Tablet,2,18000,0,Electronics,Regular
6,7,2025-01-07,South,Meena,Charger,6,500,0,Accessories,New
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular
8,9,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular
9,10,2025-01-10,East,Karan,Keyboard,5,1000,0,Accessories,New
10,11,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular
11,12,2025-01-12,North,Meena,Mouse,4,850,5,Accessories,New
12,13,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular
13,14,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New
14,15,2025-01-15,North,Karan,Charger,5,550,0,Accessories,Regular
15,16,2025-01-16,South,Rahul,Keyboard,4,1100,0,Accessories,New
16,17,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular
17,18,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New
18,19,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular
19,20,2025-01-20,South,Karan,Mouse,6,750,0,Accessories,New

In [ ]:
1. Calculate Total Sales Amount for each transaction using a new column
2. Find total sales by each Region.
3. Display all transactions where Discount is greater than 5%.
4. Group data by Category and find the average UnitPrice for each.
5. Find the top 2 SalesPersons with the highest total sales amount.
6. Filter records for only Electronics category where sales are above ₹50,000.
7. Sort the dataset by Date and SalesPerson in ascending order.
8. Find the number of transactions for each CustomerType (Regular vs New).
9. Get the most frequently sold product in each region.
10. Pivot Table: Create a pivot table showing total sales by Region and Category.

In [20]:
 #Calculate Total Sales Amount for each transaction using a new column
df["Total Sales Amount"]=(df["Quantity"]*df["UnitPrice"])*(1-df["Discount"]/100)
df

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType,Total Sales Amount
0,1,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular,114000.0
1,2,2025-01-02,South,Meena,Mouse,5,800,0,Accessories,New,4000.0
2,3,2025-01-03,East,Ajay,Keyboard,3,1200,10,Accessories,Regular,3240.0
3,4,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular,62000.0
4,5,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New,95000.0
5,6,2025-01-06,East,Rahul,Tablet,2,18000,0,Electronics,Regular,36000.0
6,7,2025-01-07,South,Meena,Charger,6,500,0,Accessories,New,3000.0
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular,156600.0
8,9,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular,51300.0
9,10,2025-01-10,East,Karan,Keyboard,5,1000,0,Accessories,New,5000.0
10,11,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular,61000.0
11,12,2025-01-12,North,Meena,Mouse,4,850,5,Accessories,New,3230.0
12,13,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular,51300.0
13,14,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New,126000.0
14,15,2025-01-15,North,Karan,Charger,5,550,0,Accessories,Regular,2750.0
15,16,2025-01-16,South,Rahul,Keyboard,4,1100,0,Accessories,New,4400.0
16,17,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular,74100.0
17,18,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New,114000.0
18,19,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular,66600.0
19,20,2025-01-20,South,Karan,Mouse,6,750,0,Accessories,New,4500.0

In [21]:
#Find total sales by each Region.
df["Total Sales Amount"].groupby(df["Region"]).sum()

Region
East     169640.0
North    438180.0
South     76900.0
West     353300.0
Name: Total Sales Amount, dtype: float64

In [22]:
#Display all transactions where Discount is greater than 5%.
df[df["Discount"]>5]

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType,Total Sales Amount
2,3,2025-01-03,East,Ajay,Keyboard,3,1200,10,Accessories,Regular,3240.0
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular,156600.0
12,13,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular,51300.0
18,19,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular,66600.0

In [23]:
#Group data by Category and find the average UnitPrice for each.
df["UnitPrice"].groupby(df["Category"]).mean()

Category
Accessories      843.750000
Electronics    41458.333333
Name: UnitPrice, dtype: float64

In [37]:
#Find the top 2 SalesPersons with the highest total sales amount.

df["Total Sales Amount"].groupby(df["SalesPerson"]).sum().nlargest(2)

SalesPerson
Priya    383900.0
Ajay     247140.0
Name: Total Sales Amount, dtype: float64

In [49]:
#Filter records for only Electronics category where sales are above ₹50,000.

df[(df["Category"]=="Electronics") & (df["Total Sales Amount"]>50000)]

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType,Total Sales Amount
0,1,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular,114000.0
3,4,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular,62000.0
4,5,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New,95000.0
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular,156600.0
8,9,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular,51300.0
10,11,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular,61000.0
12,13,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular,51300.0
13,14,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New,126000.0
16,17,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular,74100.0
17,18,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New,114000.0
18,19,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular,66600.0

In [54]:
#Sort the dataset by Date and SalesPerson in ascending order.
df.sort_values(["Date","SalesPerson"], ascending=True)

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType,Total Sales Amount
0,1,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular,114000.0
1,2,2025-01-02,South,Meena,Mouse,5,800,0,Accessories,New,4000.0
2,3,2025-01-03,East,Ajay,Keyboard,3,1200,10,Accessories,Regular,3240.0
3,4,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular,62000.0
4,5,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New,95000.0
5,6,2025-01-06,East,Rahul,Tablet,2,18000,0,Electronics,Regular,36000.0
6,7,2025-01-07,South,Meena,Charger,6,500,0,Accessories,New,3000.0
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular,156600.0
8,9,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular,51300.0
9,10,2025-01-10,East,Karan,Keyboard,5,1000,0,Accessories,New,5000.0
10,11,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular,61000.0
11,12,2025-01-12,North,Meena,Mouse,4,850,5,Accessories,New,3230.0
12,13,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular,51300.0
13,14,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New,126000.0
14,15,2025-01-15,North,Karan,Charger,5,550,0,Accessories,Regular,2750.0
15,16,2025-01-16,South,Rahul,Keyboard,4,1100,0,Accessories,New,4400.0
16,17,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular,74100.0
17,18,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New,114000.0
18,19,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular,66600.0
19,20,2025-01-20,South,Karan,Mouse,6,750,0,Accessories,New,4500.0

In [62]:
#Find the number of transactions for each CustomerType (Regular vs New).
df["CustomerType"].groupby(df["CustomerType"]).count()

CustomerType
New         9
Regular    11
Name: CustomerType, dtype: int64

In [70]:
#Get the most frequently sold product in each region.
df.groupby(["Region"])["Product"].agg(lambda x: x.mode()[0])

Region
East     Keyboard
North      Laptop
South       Mouse
West       Laptop
Name: Product, dtype: object

In [ ]:
#Pivot Table: Create a pivot table showing total sales by Region and Category.
pd.pivot_table(df,values=["Total Sales Amount"],index=["Region"],columns=["Category"],aggfunc="sum")